spring:
  cache:
    redis:
      time-to-live: 600000 # 10 minutes
      key-prefix: 'ecommerce:cache:'
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: appuser
    password: apppass
    driver-class-name: oracle.jdbc.OracleDriver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080